[package]
name = "oxmark"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
nucleo-matcher = "0.3.1"
ratatui = "0.29.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
tui-textarea = "0.7.0"
